version: '3'
services:
  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:4.4.3
    links:
      - mongodb
    volumes:
      - ./mongo_seed:/mongo_seed
    command:
      /mongo_seed/import.sh

  products1:
    build: ./
    depends_on:
      - 'mongo_seed'
    links:
      - mongodb
    ports:
      - '3000:3000'

  products2:
    build: ./
    depends_on:
      - 'mongo_seed'
    links:
      - mongodb
    ports:
      - '3001:3000'

  nginx:
    build: ./nginx
    depends_on:
      - products1
      - products2
    ports:
      - '8080:8080'