version: '3'
services:
  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017

  mongo_seed:
    image: mongo:4.4.3
    links:
      - mongodb
    volumes:
      - ./mongo_seed:/mongo_seed
    command:
      /mongo_seed/import.sh

  products:
    build: ./
    depends_on:
      - 'mongo_seed'
    links:
      - mongodb
    ports:
      - '3000:3000'