version: '3'
services:
  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017
    volumes:
      - /Users/jeffrey/Documents/HRSF133/SDC/data:/data/db

  products1:
    build: ./
    # image: productsapi_products1
    depends_on:
      - 'mongodb'
    links:
      - mongodb:mongodb
    ports:
      - '3000:3000'
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "run", "server"]

  products2:
    build: ./
    # image: productsapi_products2
    depends_on:
      - 'mongodb'
    links:
      - mongodb:mongodb
    ports:
      - '3001:3000'
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "run", "server"]

  products3:
    build: ./
    # image: productsapi_products2
    depends_on:
      - 'mongodb'
    links:
      - mongodb:mongodb
    ports:
      - '3002:3000'
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "run", "server"]

  nginx:
    build: ./nginx
    depends_on:
      - products1
      - products2
      - products3
    ports:
      - '8080:80'